// tailwind.config.js
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        header: {
          background: 'var(--header-background)',
          text: 'var(--header-text)',
        },
        primary: {
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600-main)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
          950: 'var(--primary-950)',
        },
        secondary: {
          50: 'var(--secondary-50)',
          100: 'var(--secondary-100)',
          200: 'var(--secondary-200)',
          300: 'var(--secondary-300)',
          400: 'var(--secondary-400)',
          500: 'var(--secondary-500)',
          600: 'var(--secondary-600-main)',
          700: 'var(--secondary-700)',
          800: 'var(--secondary-800)',
          900: 'var(--secondary-900)',
          950: 'var(--secondary-950)',
        },
        neutral: {
          50: 'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600-main)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          950: 'var(--neutral-950)',
        },
        success: {
          50: 'var(--success-50)',
          100: 'var(--success-100)',
          200: 'var(--success-200)',
          300: 'var(--success-300)',
          400: 'var(--success-400)',
          500: 'var(--success-500)',
          600: 'var(--success-600)',
          700: 'var(--success-700)',
          800: 'var(--success-800)',
          900: 'var(--success-900)',
          950: 'var(--success-950)',
        },
        warning: {
          50: 'var(--warning-50)',
          100: 'var(--warning-100)',
          200: 'var(--warning-200)',
          300: 'var(--warning-300)',
          400: 'var(--warning-400)',
          500: 'var(--warning-500)',
          600: 'var(--warning-600)',
          700: 'var(--warning-700)',
          800: 'var(--warning-800)',
          900: 'var(--warning-900)',
          950: 'var(--warning-950)',
        },
        error: {
          50: 'var(--error-50)',
          100: 'var(--error-100)',
          200: 'var(--error-200)',
          300: 'var(--error-300)',
          400: 'var(--error-400)',
          500: 'var(--error-500)',
          600: 'var(--error-600)',
          700: 'var(--error-700)',
          800: 'var(--error-800)',
          900: 'var(--error-900)',
          950: 'var(--error-950)',
        },
        surface: {
          background: 'var(--surface-background)',
          borders: 'var(--surface-borders)',
          container: 'var(--surface-container)',
          'container-high': 'var(--surface-container-high)',
          'container-low': 'var(--surface-container-low)',
          'container-lowest': 'var(--surface-container-lowest)',
          'container-highest': 'var(--surface-contianer-highest)',
          surface: 'var(--surface-surface)',
        },
        indicators: {
          aqua: 'var(--indicators-aqua)',
          black: 'var(--indicators-black)',
          blue: 'var(--indicators-blue)',
          brown: 'var(--indicators-brown)',
          gray: 'var(--indicators-gray)',
          green: 'var(--indicators-green)',
          orange: 'var(--indicators-orange)',
          pink: 'var(--indicators-pink)',
          purple: 'var(--indicators-purple)',
          red: 'var(--indicators-red)',
          white: 'var(--indicators-white)',
          yellow: 'var(--indicators-yellow)',
        },
        opacity: {
          'container-20': 'var(--opacity-container-20)',
          'container-40': 'var(--opacity-container-40)',
          'outline-8': 'var(--opacity-outline-8)',
          'outline-12': 'var(--opacity-outline-12)',
          'outline-16': 'var(--opacity-outline-16)',
          'primary-8': 'var(--opacity-primary-8)',
          'primary-12': 'var(--opacity-primary-12)',
          'primary-16': 'var(--opacity-primary-16)',
          'surface-8': 'var(--opacity-surface-8)',
          'surface-12': 'var(--opacity-surface-12)',
          'surface-16': 'var(--opacity-surface-16)',
        },
      },
    },
  },
  plugins: [],
};