import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

import Header from "../components/layout/Header"

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`text-xl ${poppins.className}`}>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
                                          